name: Build
on:
  - push

jobs:
  Typecheck:
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/master'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Cache yarn
        uses: actions/cache@v1
        with:
          key: v1_node14.x_ubuntu-latest_${{ github.ref }}_yarn
          path: .yarn/cache
          restore-keys: v1_node14.x_ubuntu-latest_refs/heads/master_yarn
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          key: v1_node14.x_ubuntu-latest_${{ github.ref }}_node-modules
          path: .yarn/cache
          restore-keys: v1_node14.x_ubuntu-latest_refs/heads/master_node-modules
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com
      - name: Set up Yarn
        run: npm install -g yarn@^2.0.0-rc.27
      - name: Install dependencies
        run: yarn install --immutable
        env:
          YARN_ENABLE_GLOBAL_CACHE: 'false'
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Typecheck
        run: yarn run typecheck

  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Cache yarn
        uses: actions/cache@v1
        with:
          key: v1_node14.x_ubuntu-latest_${{ github.ref }}_yarn
          path: .yarn/cache
          restore-keys: v1_node14.x_ubuntu-latest_refs/heads/master_yarn
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          key: v1_node14.x_ubuntu-latest_${{ github.ref }}_node-modules
          path: .yarn/cache
          restore-keys: v1_node14.x_ubuntu-latest_refs/heads/master_node-modules
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com
      - name: Set up Yarn
        run: npm install -g yarn@^2.0.0-rc.27
      - name: Install dependencies
        run: yarn install --immutable
        env:
          YARN_ENABLE_GLOBAL_CACHE: 'false'
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint
        run: yarn run lint

  ProdBuild:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Cache yarn
        uses: actions/cache@v1
        with:
          key: v1_node14.x_ubuntu-latest_${{ github.ref }}_yarn
          path: .yarn/cache
          restore-keys: v1_node14.x_ubuntu-latest_refs/heads/master_yarn
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          key: v1_node14.x_ubuntu-latest_${{ github.ref }}_node-modules
          path: .yarn/cache
          restore-keys: v1_node14.x_ubuntu-latest_refs/heads/master_node-modules
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com
      - name: Set up Yarn
        run: npm install -g yarn@^2.0.0-rc.27
      - name: Install dependencies
        run: yarn install --immutable
        env:
          YARN_ENABLE_GLOBAL_CACHE: 'false'
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: yarn run rollup:prod
        env:
          NODE_ENV: production
          CI: 'true'
      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          path: dist
          name: dist

  Deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master'}}
    needs:
      - ProdBuild
      - Lint
    steps:
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Check Github pages status
        uses: crazy-max/ghaction-github-status@v1
        with:
          pages_threshold: major_outage
      - name: Publish
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
